spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:database
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

jwt:
  secret-key: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
  expiration: 3600000  # ms, 1시간
  issuer: wade

payment-api:
  toss:
    secret-key: "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6:"
    base-url: https://api.tosspayments.com
    connection-timeout: 3
    read-timeout: 30
